added log-transform argument to normalize function
theislab/scib pull request #149
Opened 2020-08-27 14:33 UTC by LisaSikkema

good to make explicit that log-transformation is performed. Set default to True, for compatibility with rest of scripts.

2020-08-27 15:03 UTC, danielStrobl approved these changes
Looks good!

2020-08-27 15:04 UTC, danielStrobl commented on scIB/preprocessing.py
> +    if logtransform == True:
I think you could just do `if logtransform:` here

2020-08-27 16:15 UTC, LuckyMD requested changes
a little simplification of the code needed :)

2020-08-27 16:15 UTC, LuckyMD commented on scIB/preprocessing.py
> +def normalize(adata, min_mean = 0.1, logtransform=True):
could we turn this argument into the simpler `log=True`?

2020-08-28 13:44 UTC, LuckyMD approved these changes

2020-08-28 13:44 UTC, LuckyMD commented
Thanks a lot @LisaSikkema !

2020-08-28 13:44 UTC, closed without merging